version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - noctx
    - perfsprint
    - revive
    - unconvert
    - usestdlibvars
    - wastedassign

formatters:
  enable:
    - gofmt
    - goimports
