---
name: build.docker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build -ldflags="-w -s" .

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: test
        run: go test -v

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: prometheus-dnssec-exporter
          path: prometheus-dnssec-exporter

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          haraldkoch/prometheus-dnssec-exporter
          # ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: prometheus-dnssec-exporter

    - name: executable
      run: chmod +x prometheus-dnssec-exporter

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Docker registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
